title: Jean Decian
author: Jean Decian
email_personnal: jeandecian{at}hotmail.fr
email_school: jean.decian{at}polymtl.ca
email_work: jean.decian{at}crim.ca
description: > # this means to ignore newlines until "show_excerpts:"
  Étudiant en génie informatique.

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this

social:
  github:  jeandecian
  linkedin: jeandecian
  # facebook: jeandecian
  # instagram: jeandecian
  # twitter: jeandecian

minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
